FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

FROM gcr.io/distroless/nodejs18-debian11

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000

CMD ["app.js"]
